const PROJECTS = [
  {
    id: "cric-o-nut",
    title: "Cric-o-nut",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "A two-part slow feeder that can be hung from a carabiner to facilitate slow cricket release for arboreal insectivores.",
    tools: ["FDM Printer"],
    taxa: ["Birds", "Small Mammals"],
    targetBehavior: ["Foraging"],
    species: ["Slow loris", "Azure-winged magpie", "Bush baby"],
    complexity: "Simple",
    files: ["3MF"],
    notes: "",
    downloadUrl: "#"
  },
  {
    id: "pyramid",
    title: "Pyramid",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "A 3D printed slow feeder that can be hung from perching. Contains nubs to encourage licking and arboreal foraging behavior.",
    tools: ["FDM Printer"],
    taxa: ["Small Primates", "Birds"],
    targetBehavior: ["Foraging", "Climbing"],
    species: ["Ruffed lemur", "Guenon"],
    complexity: "Simple",
    files: ["3MF"],
    notes: "Epoxy sealing recommended for sanitation.",
    downloadUrl: "#"
  },
  {
    id: "lotus-pod",
    title: "Lotus Pod",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "A 3D printed lotus pod with tapering holes designed to extend foraging duration and promote object manipulation. Can be hung or placed on the ground.",
    tools: ["FDM Printer"],
    taxa: ["Small Primates", "Ant Eaters", "Birds"],
    targetBehavior: ["Foraging", "Object Manipulation", "Extractive Foraging"],
    species: [],
    complexity: "Simple",
    files: ["3MF"],
    notes: "Epoxy sealing recommended for sanitation.",
    downloadUrl: "#"
  },
  {
    id: "table-barriers",
    title: "Table Barriers",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "Barriers that clip onto tables to allow safe presentation of interpretation animals on elevated surfaces. Not a replacement for proper attention and animal handling, but provide an extra layer of safety against potential falls.",
    tools: ["FDM Printer", "Laser Cutter"],
    taxa: ["Ectotherms", "Testudines", "Snakes", "Lizards"],
    targetBehavior: ["Presentation", "Exploration", "Animal Health"],
    species: ["Indian star tortoise", "Pancake tortoise", "Legless lizard", "Blue-tongue skink", "Hedgehog tenrec"],
    complexity: "Complex Kit",
    files: ["3MF", "PDF", "DXF", "BOM"],
    notes: "",
    downloadUrl: "#"
  },
  {
    id: "frut",
    title: "Frut",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "A 3D printed hanging food holder that allows care staff to promote food processing by placing leafy greens around high-value food items in the center.",
    tools: ["FDM Printer"],
    taxa: ["Small Primates", "Birds"],
    targetBehavior: ["Foraging", "Ripping and Tearing", "Food Processing"],
    species: ["Guenon", "Azure-winged magpie"],
    complexity: "Simple",
    files: ["3MF"],
    notes: "Epoxy sealing recommended for sanitation.",
    downloadUrl: "#"
  },
  {
    id: "anti-ant-stump",
    title: "Anti-ant Stump",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "A 3D printed stump that allows keepers to place food in a bowl surrounded by a water moat to prevent ants from accessing it.",
    tools: ["FDM Printer"],
    taxa: ["Birds"],
    targetBehavior: ["Animal Health"],
    species: ["Azure-winged magpie"],
    complexity: "Simple",
    files: ["STL"],
    notes: "Epoxy sealing required for watertightness.",
    downloadUrl: "#"
  },
  {
    id: "woodpecker-log",
    title: "Woodpecker Log",
    author: "Dylan Baldridge",
    contributorZoo: "Memphis Zoo",
    description: "A combination of a 3D printed sleeve and paper wrapped around a PVC interior, allowing animals to engage in extractive woodpecker-like foraging behavior.",
    tools: ["FDM Printer", "Drill", "Dremel"],
    taxa: ["Birds", "Small Mammals", "Small Primates", "Ectotherms"],
    targetBehavior: ["Foraging", "Ripping and Tearing", "Extractive Foraging"],
    species: ["Emerald tree monitor"],
    complexity: "Intermediate",
    files: ["3MF", "PDF", "BOM"],
    notes: "",
    downloadUrl: "#"
  }
];
